package main

import "github.com/bwmarrin/discordgo"

const imageURL = "https://raw.githubusercontent.com/BluesLion/BlackCatHelo/master/images/tarot/"

var TarotResults = []string{
	"愚者 ＋\n" + imageURL + "00.jpg",
	"魔術師 ＋\n" + imageURL + "01.jpg",
	"女祭司 ＋\n" + imageURL + "02.jpg",
	"女皇 ＋\n" + imageURL + "03.jpg",
	"皇帝 ＋\n" + imageURL + "04.jpg",
	"教皇 ＋\n" + imageURL + "05.jpg",
	"戀人 ＋\n" + imageURL + "06.jpg",
	"戰車 ＋\n" + imageURL + "07.jpg",
	"力量 ＋\n" + imageURL + "08.jpg",
	"隱者 ＋\n" + imageURL + "09.jpg",
	"命運之輪 ＋\n" + imageURL + "10.jpg",
	"正義 ＋\n" + imageURL + "11.jpg",
	"吊人 ＋\n" + imageURL + "12.jpg",
	"死神 ＋\n" + imageURL + "13.jpg",
	"節制 ＋\n" + imageURL + "14.jpg",
	"惡魔 ＋\n" + imageURL + "15.jpg",
	"高塔 ＋\n" + imageURL + "16.jpg",
	"星星 ＋\n" + imageURL + "17.jpg",
	"月亮 ＋\n" + imageURL + "18.jpg",
	"太陽 ＋\n" + imageURL + "19.jpg",
	"審判 ＋\n" + imageURL + "20.jpg",
	"世界 ＋\n" + imageURL + "21.jpg",
	"愚者 －\n" + imageURL + "00-Re.jpg",
	"魔術師 －\n" + imageURL + "01-Re.jpg",
	"女祭司 －\n" + imageURL + "02-Re.jpg",
	"女皇 －\n" + imageURL + "03-Re.jpg",
	"皇帝 －\n" + imageURL + "04-Re.jpg",
	"教皇 －\n" + imageURL + "05-Re.jpg",
	"戀人 －\n" + imageURL + "06-Re.jpg",
	"戰車 －\n" + imageURL + "07-Re.jpg",
	"力量 －\n" + imageURL + "08-Re.jpg",
	"隱者 －\n" + imageURL + "09-Re.jpg",
	"命運之輪 －\n" + imageURL + "10-Re.jpg",
	"正義 －\n" + imageURL + "11-Re.jpg",
	"吊人 －\n" + imageURL + "12-Re.jpg",
	"死神 －\n" + imageURL + "13-Re.jpg",
	"節制 －\n" + imageURL + "14-Re.jpg",
	"惡魔 －\n" + imageURL + "15-Re.jpg",
	"高塔 －\n" + imageURL + "16-Re.jpg",
	"星星 －\n" + imageURL + "17-Re.jpg",
	"月亮 －\n" + imageURL + "18-Re.jpg",
	"太陽 －\n" + imageURL + "19-Re.jpg",
	"審判 －\n" + imageURL + "20-Re.jpg",
	"世界 －\n" + imageURL + "21-Re.jpg",
	"聖杯一 ＋\n" + imageURL + "CUPS_01.jpg",
	"聖杯二 ＋\n" + imageURL + "CUPS_02.jpg",
	"聖杯三 ＋\n" + imageURL + "CUPS_03.jpg",
	"聖杯四 ＋\n" + imageURL + "CUPS_04.jpg",
	"聖杯五 ＋\n" + imageURL + "CUPS_05.jpg",
	"聖杯六 ＋\n" + imageURL + "CUPS_06.jpg",
	"聖杯七 ＋\n" + imageURL + "CUPS_07.jpg",
	"聖杯八 ＋\n" + imageURL + "CUPS_08.jpg",
	"聖杯九 ＋\n" + imageURL + "CUPS_09.jpg",
	"聖杯十 ＋\n" + imageURL + "CUPS_10.jpg",
	"聖杯國王 ＋\n" + imageURL + "CUPS_KING.jpg",
	"聖杯騎士 ＋\n" + imageURL + "CUPS_KNIGHT.jpg",
	"聖杯侍者 ＋\n" + imageURL + "CUPS_PAGE.jpg",
	"聖杯皇后 ＋\n" + imageURL + "CUPS_QUEEN.jpg",
	"錢幣一 ＋\n" + imageURL + "PANTA_01.jpg",
	"錢幣二 ＋\n" + imageURL + "PANTA_02.jpg",
	"錢幣三 ＋\n" + imageURL + "PANTA_03.jpg",
	"錢幣四 ＋\n" + imageURL + "PANTA_04.jpg",
	"錢幣五 ＋\n" + imageURL + "PANTA_05.jpg",
	"錢幣六 ＋\n" + imageURL + "PANTA_06.jpg",
	"錢幣七 ＋\n" + imageURL + "PANTA_07.jpg",
	"錢幣八 ＋\n" + imageURL + "PANTA_08.jpg",
	"錢幣九 ＋\n" + imageURL + "PANTA_09.jpg",
	"錢幣十 ＋\n" + imageURL + "PANTA_10.jpg",
	"錢幣國王 ＋\n" + imageURL + "PANTA_KING.jpg",
	"錢幣騎士 ＋\n" + imageURL + "PANTA_KNIGHT.jpg",
	"錢幣侍者 ＋\n" + imageURL + "PANTA_PAGE.jpg",
	"錢幣皇后 ＋\n" + imageURL + "PANTA_QUEEN.jpg",
	"寶劍一 ＋\n" + imageURL + "SWORDS_01.jpg",
	"寶劍二 ＋\n" + imageURL + "SWORDS_02.jpg",
	"寶劍三 ＋\n" + imageURL + "SWORDS_03.jpg",
	"寶劍四 ＋\n" + imageURL + "SWORDS_04.jpg",
	"寶劍五 ＋\n" + imageURL + "SWORDS_05.jpg",
	"寶劍六 ＋\n" + imageURL + "SWORDS_06.jpg",
	"寶劍七 ＋\n" + imageURL + "SWORDS_07.jpg",
	"寶劍八 ＋\n" + imageURL + "SWORDS_08.jpg",
	"寶劍九 ＋\n" + imageURL + "SWORDS_09.jpg",
	"寶劍十 ＋\n" + imageURL + "SWORDS_10.jpg",
	"寶劍國王 ＋\n" + imageURL + "SWORDS_KING.jpg",
	"寶劍騎士 ＋\n" + imageURL + "SWORDS_KNIGHT.jpg",
	"寶劍侍者 ＋\n" + imageURL + "SWORDS_PAGE.jpg",
	"寶劍皇后 ＋\n" + imageURL + "SWORDS_QUEEN.jpg",
	"權杖一 ＋\n" + imageURL + "WANDS_01.jpg",
	"權杖二 ＋\n" + imageURL + "WANDS_02.jpg",
	"權杖三 ＋\n" + imageURL + "WANDS_03.jpg",
	"權杖四 ＋\n" + imageURL + "WANDS_04.jpg",
	"權杖五 ＋\n" + imageURL + "WANDS_05.jpg",
	"權杖六 ＋\n" + imageURL + "WANDS_06.jpg",
	"權杖七 ＋\n" + imageURL + "WANDS_07.jpg",
	"權杖八 ＋\n" + imageURL + "WANDS_08.jpg",
	"權杖九 ＋\n" + imageURL + "WANDS_09.jpg",
	"權杖十 ＋\n" + imageURL + "WANDS_10.jpg",
	"權杖國王 ＋\n" + imageURL + "WANDS_KING.jpg",
	"權杖騎士 ＋\n" + imageURL + "WANDS_KNIGHT.jpg",
	"權杖侍者 ＋\n" + imageURL + "WANDS_PAGE.jpg",
	"權杖皇后 ＋\n" + imageURL + "WANDS_QUEEN.jpg",
	"聖杯一 －\n" + imageURL + "CUPS_01-Re.jpg",
	"聖杯二 －\n" + imageURL + "CUPS_02-Re.jpg",
	"聖杯三 －\n" + imageURL + "CUPS_03-Re.jpg",
	"聖杯四 －\n" + imageURL + "CUPS_04-Re.jpg",
	"聖杯五 －\n" + imageURL + "CUPS_05-Re.jpg",
	"聖杯六 －\n" + imageURL + "CUPS_06-Re.jpg",
	"聖杯七 －\n" + imageURL + "CUPS_07-Re.jpg",
	"聖杯八 －\n" + imageURL + "CUPS_08-Re.jpg",
	"聖杯九 －\n" + imageURL + "CUPS_09-Re.jpg",
	"聖杯十 －\n" + imageURL + "CUPS_10-Re.jpg",
	"聖杯國王 －\n" + imageURL + "CUPS_KING-Re.jpg",
	"聖杯騎士 －\n" + imageURL + "CUPS_KNIGHT-Re.jpg",
	"聖杯侍者 －\n" + imageURL + "CUPS_PAGE-Re.jpg",
	"聖杯皇后 －\n" + imageURL + "CUPS_QUEEN-Re.jpg",
	"錢幣一 －\n" + imageURL + "PANTA_01-Re.jpg",
	"錢幣二 －\n" + imageURL + "PANTA_02-Re.jpg",
	"錢幣三 －\n" + imageURL + "PANTA_03-Re.jpg",
	"錢幣四 －\n" + imageURL + "PANTA_04-Re.jpg",
	"錢幣五 －\n" + imageURL + "PANTA_05-Re.jpg",
	"錢幣六 －\n" + imageURL + "PANTA_06-Re.jpg",
	"錢幣七 －\n" + imageURL + "PANTA_07-Re.jpg",
	"錢幣八 －\n" + imageURL + "PANTA_08-Re.jpg",
	"錢幣九 －\n" + imageURL + "PANTA_09-Re.jpg",
	"錢幣十 －\n" + imageURL + "PANTA_10-Re.jpg",
	"錢幣國王 －\n" + imageURL + "PANTA_KING-Re.jpg",
	"錢幣騎士 －\n" + imageURL + "PANTA_KNIGHT-Re.jpg",
	"錢幣侍者 －\n" + imageURL + "PANTA_PAGE-Re.jpg",
	"錢幣皇后 －\n" + imageURL + "PANTA_QUEEN-Re.jpg",
	"寶劍一 －\n" + imageURL + "SWORDS_01-Re.jpg",
	"寶劍二 －\n" + imageURL + "SWORDS_02-Re.jpg",
	"寶劍三 －\n" + imageURL + "SWORDS_03-Re.jpg",
	"寶劍四 －\n" + imageURL + "SWORDS_04-Re.jpg",
	"寶劍五 －\n" + imageURL + "SWORDS_05-Re.jpg",
	"寶劍六 －\n" + imageURL + "SWORDS_06-Re.jpg",
	"寶劍七 －\n" + imageURL + "SWORDS_07-Re.jpg",
	"寶劍八 －\n" + imageURL + "SWORDS_08-Re.jpg",
	"寶劍九 －\n" + imageURL + "SWORDS_09-Re.jpg",
	"寶劍十 －\n" + imageURL + "SWORDS_10-Re.jpg",
	"寶劍國王 －\n" + imageURL + "SWORDS_KING-Re.jpg",
	"寶劍騎士 －\n" + imageURL + "SWORDS_KNIGHT-Re.jpg",
	"寶劍侍者 －\n" + imageURL + "SWORDS_PAGE-Re.jpg",
	"寶劍皇后 －\n" + imageURL + "SWORDS_QUEEN-Re.jpg",
	"權杖一 －\n" + imageURL + "WANDS_01-Re.jpg",
	"權杖二 －\n" + imageURL + "WANDS_02-Re.jpg",
	"權杖三 －\n" + imageURL + "WANDS_03-Re.jpg",
	"權杖四 －\n" + imageURL + "WANDS_04-Re.jpg",
	"權杖五 －\n" + imageURL + "WANDS_05-Re.jpg",
	"權杖六 －\n" + imageURL + "WANDS_06-Re.jpg",
	"權杖七 －\n" + imageURL + "WANDS_07-Re.jpg",
	"權杖八 －\n" + imageURL + "WANDS_08-Re.jpg",
	"權杖九 －\n" + imageURL + "WANDS_09-Re.jpg",
	"權杖十 －\n" + imageURL + "WANDS_10-Re.jpg",
	"權杖國王 －\n" + imageURL + "WANDS_KING-Re.jpg",
	"權杖騎士 －\n" + imageURL + "WANDS_KNIGHT-Re.jpg",
	"權杖侍者 －\n" + imageURL + "WANDS_PAGE-Re.jpg",
	"權杖皇后 －\n" + imageURL + "WANDS_QUEEN-Re.jpg",
}

func TarotCond(s *discordgo.Session, m *discordgo.MessageCreate) bool {
	if m.Content == "每日塔羅" {
		return true
	}

	return false
}

func TarotGetResp(s *discordgo.Session, m *discordgo.MessageCreate) string {
	return " → " + PickOne(TarotResults)
}
